In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
dataset = pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
indep1=dataset.drop(columns=['classification'])

In [4]:
dep=dataset['classification']
dep

0      yes
1      yes
2      yes
3      yes
4      yes
      ...
394    yes
395    yes
396    yes
397    yes
398     no
Name: classification, Length: 399, dtype: object

In [5]:
indep = pd.get_dummies(indep1, drop_first=True)
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,True,False,False,False,False,False,False,True,True,False
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,True,True,False,False,False,False,False,True,False,False
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,True,True,False,False,False,False,False,True,False,False
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,True,True,False,False,False,False,False,True,False,True
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,True,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,True,True,False,False,False,False,False,True,False,False
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,True,True,False,False,True,True,False,True,False,True
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,True,True,False,False,True,True,False,False,False,False
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,True,True,False,False,True,True,False,True,False,True
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,True,True,False,False,False,False,False,True,False,False

In [6]:
dataset['classification'].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
from sklearn.model_selection import GridSearchCV
param_grid =  {'solver':['liblinear', 'newton-cg', 'saga', 'lbfgs'],
                          'penalty':['l2'], 'C': [0.1, 1, 10]}
grid = GridSearchCV(LogisticRegression(), param_grid, verbose = 3, refit = True, n_jobs = -1, scoring = 'accuracy')

grid.fit(x_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'penalty': ['l2'],
                         'solver': ['liblinear', 'newton-cg', 'saga', 'lbfgs']},
             scoring='accuracy', verbose=3)

In [11]:
re = grid.cv_results_
grid_predictions = grid.predict(x_test)


from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

print(cm)
print(clf_report)

[[51  0]
 [ 1 81]]
              precision    recall  f1-score   support

          no       0.98      1.00      0.99        51
         yes       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [12]:
from sklearn.metrics import f1_score
f1_macro = f1_score(y_test, grid_predictions, average = 'weighted')
print("the f1_macro value for best parameter {}: " . format(grid.best_params_), f1_macro)

the f1_macro value for best parameter {'C': 1, 'penalty': 'l2', 'solver': 'newton-cg'}:  0.9924946382275899

In [13]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, grid.predict_proba(x_test)[:,1])

1.0

In [16]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.013948,0.004360,0.007256,0.001536,0.1,l2,liblinear,"{'C': 0.1, 'penalty': 'l2', 'solver': 'libline...",0.944444,0.962264,0.943396,0.981132,0.962264,0.958700,0.013900,12
1,0.020779,0.005410,0.005114,0.000979,0.1,l2,newton-cg,"{'C': 0.1, 'penalty': 'l2', 'solver': 'newton-...",1.000000,0.981132,0.981132,1.000000,0.981132,0.988679,0.009243,5
2,0.041653,0.011558,0.005425,0.001322,0.1,l2,saga,"{'C': 0.1, 'penalty': 'l2', 'solver': 'saga'}",1.000000,0.981132,0.962264,1.000000,0.981132,0.984906,0.014119,8
3,0.068846,0.009057,0.003580,0.000494,0.1,l2,lbfgs,"{'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}",1.000000,0.981132,0.981132,1.000000,0.981132,0.988679,0.009243,5
4,0.005090,0.000320,0.003464,0.000312,1.0,l2,liblinear,"{'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}",0.962963,0.981132,0.962264,0.981132,0.981132,0.973725,0.009075,11
5,0.015012,0.002374,0.003820,0.000643,1.0,l2,newton-cg,"{'C': 1, 'penalty': 'l2', 'solver': 'newton-cg'}",0.981481,0.981132,0.981132,1.000000,1.000000,0.988749,0.009187,1
6,0.037938,0.001609,0.004738,0.001159,1.0,l2,saga,"{'C': 1, 'penalty': 'l2', 'solver': 'saga'}",0.981481,0.981132,0.981132,0.981132,0.981132,0.981202,0.000140,9
7,0.011937,0.001938,0.004646,0.000842,1.0,l2,lbfgs,"{'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}",0.981481,0.981132,0.981132,1.000000,1.000000,0.988749,0.009187,1
8,0.005186,0.000797,0.003165,0.000940,10.0,l2,liblinear,"{'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}",0.962963,0.981132,0.981132,1.000000,1.000000,0.985045,0.013896,7
9,0.016166,0.002191,0.003519,0.000994,10.0,l2,newton-cg,"{'C': 10, 'penalty': 'l2', 'solver': 'newton-cg'}",0.981481,0.981132,0.981132,1.000000,1.000000,0.988749,0.009187,1
10,0.026268,0.002960,0.002671,0.000324,10.0,l2,saga,"{'C': 10, 'penalty': 'l2', 'solver': 'saga'}",0.962963,0.981132,0.981132,0.981132,0.981132,0.977498,0.007268,10
11,0.009063,0.001625,0.002625,0.000954,10.0,l2,lbfgs,"{'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}",0.981481,0.981132,0.981132,1.000000,1.000000,0.988749,0.009187,1